### ISSUE TITLE
frontity.org not working in Safari 11.1

### ISSUE THREAD

**Issue by rmartinezduque** [frontity/frontity.org#100] opened 2020-04-30 15:32 UTC
**Observed behavior**
When you visit the frontity.org website in Safari 11.1 the screen goes blank.

![frontityorg-safari](https://user-images.githubusercontent.com/20700757/80729229-372e4580-8b08-11ea-8a29-25d127d55c47.png)

![frontityorg-safari02](https://user-images.githubusercontent.com/20700757/80729363-7492d300-8b08-11ea-9800-237ab603221d.png)

**Comment by michalczaplinski** [comment] 2020-04-30 23:54
This is caused by using `react-intersection-observer` without the polyfill. 

We can either rewrite those parts or simply add the [polyfill](https://www.npmjs.com/package/react-intersection-observer#polyfill). 

For now at least I chose to just add the polyfill.

**Comment by luisherranz** [comment] 2020-05-02 13:55
I cannot believe the library doesn't fail gracefully when the IO is not available, and we are actually recommending this 😓

I'm going to close this and open the bug in the frontity repo.

**Comment by luisherranz** [comment] 2020-05-02 14:26
I'm against adding polyfills. I think we can go back to `@frontity/hooks/use-in-view` to generate a wrapper. That wrapper can fail gracefully and also should return information to let the user know if the IO is available or not.

```js
import { useInView } from "react-intersection-observer";

export default (options) => {
  if (typeof window.IntersectionObserver === "undefined") {
    // Unsupported, return no `ref` and default `inView` true value.
    return { inView: true, ref: undefined, supported: false };
  }
  const [ref, inView] = useInView(options);
  return { ref, inView, supported: true };
};
```

This way, components using this for lazy loading don't need to do anything special because `inView` is going to be true, and components doing more complex stuff, like infinite scroll for example, can check if `supported` is true or not.

For example, the `useInfiniteScrollPagination` hook should always return the first page and deactivate the infinite scroll if the IntersectionObserver is not available:

```js
import useInView from "@frontity/hooks/use-in-view";

const useInfiniteScrollPagination = (options) => {
  const { ref, supported, inView } = useInView();

  if (supported) {
    // Do stuff if the IntersectionObserver is available.
  } else {
    // Do stuff if the IntersectionObserver is not available.
  }
};
```

**Comment by michalczaplinski** [comment] 2020-05-04 15:51
I definitely agree that we should avoid adding polyfills as much as possible but at the same this one is 3kb so my opinion is it's worth the simplicity of just adding a polyfill and not worrying about adding an alternative implementation. I know that the polyfill comes with caveats and can not work for all use cases.

However, I saw that the way that we use the `useInView` in frontity.org does not really make sense if IO is not preset. For example, we're showing and hiding the header: https://github.com/frontity/frontity.org/blob/2ffb9abf8c6abd67dbb9139b8785e35913689f0c/packages/frontity-org-theme/src/components/headers/index.tsx#L22-L31

So, this behaviour would have to be rewritten if we decide to use the wrapper you suggested.

I ll leave that decision up to you if it still makes sense to create a wrapper and remove the polyfill, I think it would be less work just keep the polyfill 🙂

**Comment by luisherranz** [comment] 2020-05-05 07:04
> So, this behaviour would have to be rewritten if we decide to use the wrapper you suggested.

The decision, in that case, could be not to show the header if IO is not supported.

```js
// Check if this bar is visible or not.
const { ref, inView, supported } = useInView();

React.useEffect(() => {
  if (supported && inView) {
    actions.theme.showFixedHeader();
  } else {
    actions.theme.hideFixedHeader();
  }
}, [inView]);
```

**Comment by SantosGuillamot** [comment] 2020-05-07 08:15
Could you confirm these couple of questions to set the priority please?
* It's affecting to all the browsers that don't support IntersectionObserver right? According to [canisue](https://caniuse.com/#feat=intersectionobserver), 8-9% aprox.
* [This fix](https://caniuse.com/#feat=intersectionobserver) proposed by Michal is not valid anymore because we're going to try to avoid polyfills right?

**Comment by luisherranz** [comment] 2020-05-07 11:23
> It's affecting to all the browsers that don't support IntersectionObserver right? According to canisue, 8-9% aprox.

Yes.

> This fix proposed by Michal is not valid anymore because we're going to try to avoid polyfills right?

It is valid. We can merge it now to solve this, maybe in the future use the hook that @orballo is working on.

**Comment by orballo** [comment] 2020-05-08 13:31
After tinkering with `useInfiniteScroll` I think the `useInView` is ready, though, I couldn't really test it against Safari :/

**Closed** 2020-05-12 14:06 UTC
Labels: awaiting-priority, bug
